=== 전체 목록 (/teams/*)
[cols=2*]
|===
| 기능 | API

| <<1. 팀 생성>> | [POST] /teams
| <<2. 팀 이미지 업로드>> | [POST] /teams/{teamId}
| <<3 ~ 4. 팀 결과 요청>> | [GET] /teams/{teamId}/results
| <<5. 팀 ID 조회>> | [GET] /teams/names/{teamName}

|===

=== 1. 팀 생성

API : `POST /teams`

Request Body 로 팀 구성원 수를 보내야 합니다.

==== 200 OK

===== Request

operation::team_create_test/create_team_success[snippets='http-request,request-body,request-fields']

===== Response

operation::team_create_test/create_team_success[snippets='http-response,response-body,response-fields']

=== 2. 팀 이미지 업로드

API : `POST /teams/{teamId}`

Request Body 로 업로드가 완료된 Image URL을 보내야 합니다.

==== 200 OK

===== Request

operation::team_upload_test/upload_team_success[snippets='http-request,request-body,request-fields']

===== Response(팀원들이 모두 이미지 업로드가 안 된 상태일 때)

operation::team_upload_test/upload_team_success[snippets='http-response,response-body,response-fields']

===== Response(팀원들이 모두 이미지 업로드가 된 상태일 때)

operation::team_upload_test/completed_upload_team_success[snippets='response-body,response-fields']

=== 3. 팀 결과 요청 (auth_code 미입력)

API : `GET /teams/{teamId}/results`

==== 200 OK

===== Request

operation::team_result_test/result_team_success[snippets='http-request']

===== Response(이미지 제출 수 충족, 성공, auth_code와 상관 없음)

operation::team_result_test/result_team_success[snippets='http-response,response-body,response-fields']

===== Response(이미지 제출 수 미충족, 실패, auth_code와 상관 없음)

operation::team_result_test/result_team_fail[snippets='response-body']

=== 4. 팀 결과 요청 (auth_code 입력)

API : `GET /teams/{teamId}/results?auth_code=1234`

- auth_code : 4자리 숫자로 구성됩니다. 각 자리는 0~9에 해당하는 정수여야 합니다.

==== 200 OK

===== Request(이미지 제출 수 미충족, 성공, 올바른 auth_code를 입력한 경우)

operation::team_result_test/result_team_with_auth_code[snippets='http-request']


===== Response(이미지 제출 수 미충족, 성공, 올바른 auth_code를 입력한 경우)

operation::team_result_test/result_team_with_auth_code[snippets='response-body']


===== Request(이미지 제출 수 미충족, 실패, 잘못된 auth_code를 입력한 경우)

operation::team_result_test/result_team_with_wrong_auth_code[snippets='http-request']

===== Response(이미지 제출 수 미충족, 실패, 잘못된 auth_code를 입력한 경우)

operation::team_result_test/result_team_with_wrong_auth_code[snippets='response-body']

=== 5. 팀 ID 조회

API : `GET /teams/names/{teamName}`

teamName을 Path Parameter로 넣어야 합니다.

==== 200 OK

===== Request

operation::team_name_test/find_team_id_by_team_name[snippets='http-request']

===== Response

operation::team_name_test/find_team_id_by_team_name[snippets='http-response,response-body,response-fields']
