name: spring-deploy-to-ec2

on:
  push:
    branches: [ main ]
  
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mogong
    
    steps:
      - uses: actions/checkout@v3

      - name: Spring - Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
      
      - name: switch env file
        run: |
          cat /dev/null > ./src/main/resources/application.yml
          cat /dev/null > ./src/test/resources/application.yml
          echo "${{ secrets.APPLICATION_YML }}" >> ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_YML }}" >> ./src/test/resources/application.yml

      - name: Spring - Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Spring-application build 
        run: ./gradlew build
      
       # Docker
      - name: Docker - Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Docker - Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      - name: Docker - Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./mogong
          push: true
          tags: gkstjr5731/mogong:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Depoly in AWS ec2 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: | 
            sudo docker system prune -f
            sudo docker pull gkstjr5731/mogong:latest
            sudo docker stop mogong-spring-server && sudo docker rm mogong-spring-server
            sudo docker run -d --name mogong-spring-server -p 443:8080 gkstjr5731/mogong:latest
            sleep 60
            sudo docker inspect -f {{.State.Pid}} mogong-spring-server | grep -v '^0'
